/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-10-22 15:40:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>è¯·æ±åæ°ä¼ éåæ¥æ¶é®é¢</title>\r\n");
      out.write("    \r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("    <meta http-equiv=\"description\" content=\"this is my page\">\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  <h3>GETæ¹å¼æäº¤</h3>\r\n");
      out.write("    <form action=\"/day09/demo5\" method=\"GET\">\r\n");
      out.write("        ç¨æ·åï¼<input type=\"text\" name=\"name\"/><br/>\r\n");
      out.write("        å¯ç ï¼<input type=\"password\" name=\"password\"/><br/>\r\n");
      out.write("        æ§å«ï¼\r\n");
      out.write("        <input type=\"radio\" name=\"gender\" value=\"ç·\"/>ç·\r\n");
      out.write("        <input type=\"radio\" name=\"gender\" value=\"å¥³\"/>å¥³<br/>\r\n");
      out.write("        ç±è´¯ï¼\r\n");
      out.write("            <select name=\"jiguan\">\r\n");
      out.write("                <option value=\"å¹¿ä¸\">å¹¿ä¸</option>\r\n");
      out.write("                <option value=\"å¹¿è¥¿\">å¹¿è¥¿</option>\r\n");
      out.write("                <option value=\"æ¹å\">æ¹å</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <br/>\r\n");
      out.write("        ç±å¥½ï¼\r\n");
      out.write("        <input type=\"checkbox\" name=\"habit\" value=\"ç¯®ç\"/>ç¯®ç\r\n");
      out.write("        <input type=\"checkbox\" name=\"habit\" value=\"è¶³ç\"/>è¶³ç\r\n");
      out.write("        <input type=\"checkbox\" name=\"habit\" value=\"ç¾½æ¯ç\"/>ç¾½æ¯ç<br/>\r\n");
      out.write("        ä¸ªäººç®ä»ï¼\r\n");
      out.write("        <textarea rows=\"5\" cols=\"10\" name=\"info\"></textarea><br/>\r\n");
      out.write("        <!-- éèå -->\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"001\"/>\r\n");
      out.write("        <input type=\"submit\" value=\"æäº¤\"/>\r\n");
      out.write("    </form>\r\n");
      out.write("    <hr/>\r\n");
      out.write("    \r\n");
      out.write("    <h3>POSTæ¹å¼æäº¤</h3>\r\n");
      out.write("    <form action=\"/day09/demo5\" method=\"POST\">\r\n");
      out.write("        ç¨æ·åï¼<input type=\"text\" name=\"name\"/><br/>\r\n");
      out.write("        å¯ç ï¼<input type=\"password\" name=\"password\"/><br/>\r\n");
      out.write("        æ§å«ï¼\r\n");
      out.write("        <input type=\"radio\" name=\"gender\" value=\"ç·\"/>ç·\r\n");
      out.write("        <input type=\"radio\" name=\"gender\" value=\"å¥³\"/>å¥³<br/>\r\n");
      out.write("        ç±è´¯ï¼\r\n");
      out.write("            <select name=\"jiguan\">\r\n");
      out.write("                <option value=\"å¹¿ä¸\">å¹¿ä¸</option>\r\n");
      out.write("                <option value=\"å¹¿è¥¿\">å¹¿è¥¿</option>\r\n");
      out.write("                <option value=\"æ¹å\">æ¹å</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <br/>\r\n");
      out.write("        ç±å¥½ï¼\r\n");
      out.write("        <input type=\"checkbox\" name=\"hobit\" value=\"ç¯®ç\"/>ç¯®ç\r\n");
      out.write("        <input type=\"checkbox\" name=\"hobit\" value=\"è¶³ç\"/>è¶³ç\r\n");
      out.write("        <input type=\"checkbox\" name=\"hobit\" value=\"ç¾½æ¯ç\"/>ç¾½æ¯ç<br/>\r\n");
      out.write("        ä¸ªäººç®ä»ï¼\r\n");
      out.write("        <textarea rows=\"5\" cols=\"10\" name=\"info\"></textarea><br/>\r\n");
      out.write("        <!-- éèå -->\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"001\"/>\r\n");
      out.write("        <input type=\"submit\" value=\"æäº¤\"/>\r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
